
version: "3.1"
services:
  web:
    build: ./nas_be
    volumes:
      - ./nas_be/app/:/usr/src/app/
    ports:
      - "5000:5000"
    depends_on:
      - postgres_db


  postgres_db:
    environment:
      POSTGRES_USER: ivtree
      POSTGRES_PASSWORD: ivtree@123
      POSTGRES_DB: nas_db
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/docker-entrypoint-initdb.d/:ro

  nginx:
    build: ./nginx
    ports: 
      - "4000:4000"
